name: expression_de_besoins_convers
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  flutter_html: 3.0.0-beta.2
  package_info_plus: ^8.0.0
  dio: ^5.4.3+1
  url_launcher: ^6.2.6
  loading_animation_widget: ^1.2.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  google_ml_kit: ^0.18.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.0.10+1
  lq_image_utils: ^0.0.3
  path_provider: ^2.1.3
  get_cli: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo-nuxe-background.png
    - images/logo-nuxe-background.svg
    - images/connexion-img.png
    - images/logo-nuxe.png
    - images/background-convers.jpg
    - images/background-convers-transparent.png
    - images/test-background.jpg
    - images/logo-nuxe-blanc.png
    - images/background-convers-transparent-tiny.png
    - images/background-test.jpg
    - images/background-transparent.png
    - images/img-connexion.jpg

  fonts:
    - family: SackersGothicStd
      fonts:
        - asset: fonts\sackers-gothic-std-light.otf
          weight: 200
        - asset: fonts\sackers-gothic-std-medium.otf
        - asset: fonts\sackers-gothic-std-heavy.otf
          weight: 700
